class ModifierAttributes:
    attack = "attack"
    magic_attack = "magic_attack"
    defense = "defense"
    magic_defense = "magic_defense"
    heal = "heal"
    life = "life"
    luck = "luck"
    critical_percentage = "critical"  # critical_damage
    critical_percentage_reduction = "critical_reduction"
    suffer_critical_percentage = "suffer_critical"
    attack_percentage = "attack_percentage"
    skill_damage_percentage = "skill_damage_percentage"
    single_target_skill_damage_percentage = "single_target_skill_damage_percentage"
    single_target_skill_damage_reduction_percentage = (
        "single_target_skill_damage_reduction_percentage"
    )
    range_skill_damage_percentage = "range_skill_damage_percentage"
    range_skill_damage_reduction_percentage = "range_skill_damage_reduction_percentage"
    normal_attack_damage_percentage = "normal_attack_damage_percentage"
    normal_attack_damage_reduction_percentage = (
        "normal_attack_damage_reduction_percentage"
    )
    physical_penetration_percentage = "physical_penetration_percentage"
    magic_penetration_percentage = "magic_penetration_percentage"
    battle_damage_percentage = "battle_damage_percentage"
    battle_damage_reduction_percentage = "battle_damage_reduction_percentage"
    magic_attack_percentage = "magic_attack_percentage"
    defense_percentage = "defense_percentage"
    magic_defense_percentage = "magic_defense_percentage"
    physical_damage_percentage = "physical_damage_percentage"
    physical_damage_reduction_percentage = "physical_damage_reduction_percentage"
    active_damage_percentage = "active_damage_percentage"
    counterattack_damage_percentage = "counterattack_damage_percentage"
    magic_damage_percentage = "magic_damage_percentage"
    magic_damage_reduction_percentage = "magic_damage_reduction_percentage"
    heal_percentage = "heal_percentage"
    life_percentage = "life_percentage"
    luck_percentage = "luck_percentage"
    critical_damage_percentage = "critical_damage_percentage"
    critical_damage_reduction_percentage = "critical_damage_reduction_percentage"
    fixed_damage_reduction_percentage = "fixed_damage_reduction_percentage"
    move_range = "move_range"
    current_move_range = "current_move_range"
    attack_range = "attack_range"
    move_range_max = "move_range_max"
    physical_protect_range = "physical_protect_range"
    magic_protect_range = "magic_protect_range"
    counterattack_first_limit = "counterattack_first_limit"
    counterattack_range = "counterattack_range"
    range_skill_range = "range_skill_range"
    single_skill_range = "single_skill_range"

    element_attacker_multiplier = "element_attacker_multiplier"
    element_defender_multiplier = "element_defender_multiplier"

    is_passives_disabled = "passives_disabled"
    is_action_disabled = "action_disabled"
    is_counterattack_disabled = "counterattack_disabled"
    is_counterattack_first = "counterattack_first"
    is_non_selectable = "non_selectable"
    is_non_healable = "non_healable"
    is_ignore_protector = "ignore_protector"
    is_ignore_obstacle = "ignore_obstacle"
    is_ignore_block = "is_ignore_block"
    active_skill_range = "active_skill_range"
    is_active_skill_disabled = "active_skill_disabled"
    is_targetable_by_enemy = "targetable_by_enemy"
    prevent_death = "prevent_death"
    is_double_attack = "double_attack"
    is_extra_move_disabled = "extra_move_disabled"
    is_certain_skill_disabled = "certain_skill_disabled"
